from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "shared" / "schemas" / "agent-invocation.schema.json"
TS_OUT = ROOT / "frontend" / "src" / "generated" / "wireContracts.ts"
PY_OUT = ROOT / "backend" / "app" / "generated" / "wire_contracts.py"


def _union(values: list[object], language: str) -> str:
    quoted = [json.dumps(value, ensure_ascii=False) for value in values]
    return (" | " if language == "ts" else ", ").join(quoted)


def _type(spec: dict, language: str) -> str:
    if "$ref" in spec:
        name = spec["$ref"].rsplit("/", 1)[-1]
        return {"imageMask": "ImageMaskWire", "historyItem": "HistoryItemWire", "attachmentItem": "AttachmentItemWire"}[name]
    if "anyOf" in spec:
        values = [_type(item, language) for item in spec["anyOf"]]
        return (" | ".join(values) if language == "ts" else f"{' | '.join(values)}")
    if "enum" in spec:
        return _union(spec["enum"], language) if language == "ts" else "Literal[" + _union(spec["enum"], language) + "]"
    kind = spec.get("type")
    if kind == "string": return "string" if language == "ts" else "str"
    if kind == "integer": return "number" if language == "ts" else "int"
    if kind == "boolean": return "boolean" if language == "ts" else "bool"
    if kind == "null": return "null" if language == "ts" else "None"
    if kind == "array":
        item = _type(spec.get("items", {}), language)
        return f"{item}[]" if language == "ts" else f"list[{item}]"
    if kind == "object": return "Record<string, string>" if language == "ts" else "dict[str, str]"
    return "unknown" if language == "ts" else "object"


def render_ts(schema: dict) -> str:
    required = set(schema.get("required", []))
    lines = ["// Generated by scripts/generate_wire_contracts.py. Do not edit.", ""]
    for name, definition in (("ImageMaskWire", schema["$defs"]["imageMask"]), ("HistoryItemWire", schema["$defs"]["historyItem"]), ("AttachmentItemWire", schema["$defs"]["attachmentItem"])):
        lines.append(f"export interface {name} {{")
        for key, spec in definition["properties"].items(): lines.append(f"  {key}: {_type(spec, 'ts')};")
        lines.extend(["}", ""])
    lines.append("export interface AgentInvocationWire {")
    for key, spec in schema["properties"].items():
        lines.append(f"  {key}{'' if key in required else '?'}: {_type(spec, 'ts')};")
    lines.extend(["}", "", f"export const AGENT_INVOCATION_WIRE_FIELDS = {json.dumps(list(schema['properties']), ensure_ascii=False)} as const;", ""])
    return "\n".join(lines)


def render_py(schema: dict) -> str:
    required = set(schema.get("required", []))
    lines = ["# Generated by scripts/generate_wire_contracts.py. Do not edit.", "from __future__ import annotations", "", "from typing import Literal, NotRequired, TypedDict", ""]
    for name, definition in (("ImageMaskWire", schema["$defs"]["imageMask"]), ("HistoryItemWire", schema["$defs"]["historyItem"]), ("AttachmentItemWire", schema["$defs"]["attachmentItem"])):
        lines.append(f"class {name}(TypedDict):")
        for key, spec in definition["properties"].items(): lines.append(f"    {key}: {_type(spec, 'py')}")
        lines.append("")
    lines.append("class AgentInvocationWire(TypedDict):")
    for key, spec in schema["properties"].items():
        value_type = _type(spec, "py")
        lines.append(f"    {key}: {value_type if key in required else f'NotRequired[{value_type}]'}")
    lines.extend(["", f"AGENT_INVOCATION_WIRE_FIELDS = frozenset({list(schema['properties'])!r})", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    outputs = {TS_OUT: render_ts(schema), PY_OUT: render_py(schema)}
    stale = [path for path, content in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
    if args.check:
        if stale: print("Wire contracts are stale: " + ", ".join(str(path.relative_to(ROOT)) for path in stale))
        return 1 if stale else 0
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
